### ISSUE TITLE
SSR with React 17+ - ReferenceError: self is not defined

### ISSUE THREAD

**Issue by AlexITC** [japgolly/scala-graal#267]
I have tried the SSR examples with React 17 and 18, in both cases, I get the same error `ReferenceError: self is not defined`.

I have saw that `ReactSsr` defines the `window` object, maybe something similar needs to be done?

**Comment by japgolly** [comment]
Hi @AlexITC, I can't reproduce this. Can you provide more info please? The full error stack trace plus the Scala code that's failing would be very helpful to see.

Also, an I confirm that you've read through the [tutorial](https://blog.shipreq.com/post/scala_react_and_ssr_part_1)?

**Comment by AlexITC** [comment]
I have prepared a simple repo to showcase SSR (https://github.com/wiringbits/scalajs-react-ssr-demo), please check these commits:

1. Working version (react 16): https://github.com/wiringbits/scalajs-react-ssr-demo/commit/db91756a180dc7cb82c11984a65cb9b9e144d64e
2. React 17 failure: https://github.com/wiringbits/scalajs-react-ssr-demo/commit/8b38feaa1d747b0a2dbb237747bd22de2e6ece51
3. React 18 failure: https://github.com/wiringbits/scalajs-react-ssr-demo/commit/0cf03bc5ce7e6933bf649e0c70016eeaf14878d8

I confirm that I read the tutorial, in any case, I'll give it a second look.

Thanks.

**Comment by japgolly** [comment]
Wonderful, thank you! I'll check it out tomorrow

**Comment by japgolly** [comment]
Ok I know what's going on here and it's an issue between React itself and Node. As of React 17, the production build is targeted towards browsers only, and is not loadable from Node. To use SSR from a Node-based server, developers do this

```js
import React from 'react';
import ReactDOMServer from 'react-dom/server';
```

and then have their bundler do minification as part of the server's build process.

To use load React 17+ into Graal, there are two choices.
1. Use the dev builds `react.development.js` and `react-dom-server.browser.development.js`
2. Create your own production bundle for Node using this as your source:
    ```js
    export { default as React          } from 'react';
    export { default as ReactDOMServer } from 'react-dom/server';
    ```
